### ISSUE TITLE
Send and receive different currencies

### ISSUE THREAD

**Issue by justinwoo395** [cs130-w21/23#8]
## Epic
Exchanging currency is the core feature of our project. Users will be able to quickly register for accounts and login to access their saved financial information, which will leverage requests to a SQL database. After users have logged in, they will be able to select a currency and request an exchange of a selected amount to another currency. If a match is found with another user, both users will be notified and prompted to accept. Upon acceptance, the amount of each currency in each user's account will be updated accordingly.

## User Stories
- [ ] As a user, I would like to create an account so that I can store my information and money. #6
- [ ] As a user, I would like to request a currency exchange so that I can convert my money to a different currency. #7
- [ ] As a user, I would like to cancel a currency exchange request so I can prevent the execution of unwanted transactions. #12
- [ ] As a user, I would like to set a preferred exchange rate so that I can match with another user to complete the exchange. #13
